import { ColumnObject } from '@/app/t-container/t-container.type';

const DEFAULT_COLUMN: ColumnObject = {
  conNo: {
    name: 'conNo',
    label: '컨테이너 번호',
    order: 0,
    visible: true,
    width: 'w-32',
  },
  dischargeVesselName: {
    name: 'dischargeVesselName',
    label: '양하 선박',
    order: 1,
    visible: true,
    width: 'w-56',
  },
  loadingVesselName: {
    name: 'loadingVesselName',
    label: '선적 선박',
    order: 2,
    visible: true,
    width: 'w-40',
  },
  transshipmentType: {
    name: 'transshipmentType',
    label: '자/타부두',
    order: 3,
    visible: true,
    width: 'w-32',
  },
  bookingNo: {
    name: 'bookingNo',
    label: 'BK No.',
    order: 4,
    visible: true,
    width: 'w-40',
  },
  blNo: {
    name: 'blNo',
    label: 'B/L No.',
    order: 5,
    visible: true,
    width: 'w-48',
  },
  size: {
    name: 'size',
    label: '20/40 피트',
    order: 6,
    visible: true,
    width: 'w-32',
  },
  feType: {
    name: 'feType',
    label: 'F/E',
    order: 7,
    visible: true,
    width: 'w-32',
  },
  yardLocation: {
    name: 'yardLocation',
    label: '야드 위치',
    order: 8,
    visible: true,
    width: 'w-32',
  },
  referTemp: {
    name: 'referTemp',
    label: '온도(℃)',
    order: 9,
    visible: true,
    width: 'w-32',
  },
  oog: { name: 'oog', label: 'OOG', order: 10, visible: true, width: 'w-32' },
  dischargeTerminalName: {
    name: 'dischargeTerminalName',
    label: '양하 터미널',
    order: 11,
    visible: true,
    width: 'w-32',
  },
  loadingTerminalName: {
    name: 'loadingTerminalName',
    label: '선적 터미널',
    order: 12,
    visible: true,
    width: 'w-32',
  },
  dischargeCompletedAt: {
    name: 'dischargeCompletedAt',
    label: '양하 완료',
    order: 13,
    visible: true,
    width: 'w-40',
  },
  dischargeYardAt: {
    name: 'dischargeYardAt',
    label: '양하 야드',
    order: 14,
    visible: true,
    width: 'w-40',
  },
  dischargeGateOutAt: {
    name: 'dischargeGateOutAt',
    label: '양하 반출',
    order: 15,
    visible: true,
    width: 'w-40',
  },
  loadingGateInAt: {
    name: 'loadingGateInAt',
    label: '선적 반입',
    order: 16,
    visible: true,
    width: 'w-40',
  },
  loadingYardAt: {
    name: 'loadingYardAt',
    label: '선적 야드',
    order: 17,
    visible: true,
    width: 'w-40',
  },
  loadingCompletedAt: {
    name: 'loadingCompletedAt',
    label: '선적 완료',
    order: 18,
    visible: true,
    width: 'w-40',
  },
};

export { DEFAULT_COLUMN };
