import '@/app/globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2', // woff2: 폰트 파일 크기 줄이기 위해 사용
  display: 'swap', // 폰트 로딩 방식 설정 (swap: 폰트 로딩 시 대체 폰트 사용)
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      {/* body에 직접 폰트 클래스 적용 -> font-family 적용 */}
      <body className={`${pretendard.className}`}>{children}</body>
    </html>
  );
};

export { metadata };

export default RootLayout;
