const OPERATION_TYPE = {
  DISCHARGE: 'DISCHARGE',
  DISCHARGE_YARD: 'DISCHARGE_YARD',
  GATE_OUT: 'GATE_OUT',
  GATE_IN: 'GATE_IN',
  LOADING: 'LOADING',
  LOADING_YARD: 'LOADING_YARD',
};

const SELF_DOCK_OPERATION_KOREAN = {
  [OPERATION_TYPE.LOADING]: '양하',
  [OPERATION_TYPE.DISCHARGE_YARD]: '야드',
  [OPERATION_TYPE.DISCHARGE]: '선적',
};

const OTHER_DOCK_OPERATION_KOREAN = {
  [OPERATION_TYPE.LOADING]: '양하',
  [OPERATION_TYPE.LOADING_YARD]: '양하 야드',
  [OPERATION_TYPE.GATE_IN]: '양하 반출',
  [OPERATION_TYPE.GATE_OUT]: '선적 반입',
  [OPERATION_TYPE.DISCHARGE_YARD]: '선적 야드',
  [OPERATION_TYPE.DISCHARGE]: '선적 완료',
};

export {
  OPERATION_TYPE,
  OTHER_DOCK_OPERATION_KOREAN,
  SELF_DOCK_OPERATION_KOREAN,
};
